language: go
sudo: false
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

os:
  - linux
  - osx

before_install:
  - go get ./cmd/...

script:
    # build test for supported platforms
  - GOOS=linux go build ./cmd/...
  - GOOS=darwin go build ./cmd/...
  - GOOS=freebsd go build ./cmd/...
  - GOOS=windows go build ./cmd/...
  - GOARCH=386 go build ./cmd/...

   # run tests on a standard platform
  - go test -v ./...

  # run tests with the race detector as well
  - go test -race -v ./...
